FROM node:18.19.1-alpine AS build

WORKDIR /app

COPY . .

RUN npm i && npm run build

FROM node:18.19.1-alpine AS exec

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./

EXPOSE 8080

CMD ["npm", "run", "api"]